apiVersion: v1
kind: Service
metadata:
  name: people-discount-service # DNS name for other microservices and Gateway
  namespace: backend
  labels:
    app: kartingrm
    component: people-discount-service
spec:
  selector:
    app: kartingrm
    component: people-discount-service
  ports:
    - protocol: TCP
      port: 8080       # This is the service port
      targetPort: 8080 # This is the container port
  type: ClusterIP      # Internal service