apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
