apiVersion: v1
kind: Service
metadata:
  name: fee-type-service
  namespace: backend
spec:
  selector:
    app: fee-type
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
