apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: cristobalmilla/gateway-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m" # Ajustar para limitaciones de memoria, por ahora de 256 MB a 512 MB
            - name: EUREKA_HOST
              value: "eureka-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
