apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent-receipt-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rent-receipt
  template:
    metadata:
      labels:
        app: rent-receipt
    spec:
      containers:
      - name: rent-receipt-service
        image: cristobalmilla/rent-receipt-service:latest
        env:
        - name: EUREKA_HOST
          value: "eureka-service.backend.svc.cluster.local"
        - name: EUREKA_PORT
          value: "8761"
        - name: CONFIG_SERVER_URI
          value: "http://config-server.backend.svc.cluster.local:8081"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: RENT_RECEIPT_DB_NAME
          value: "KartingRMRentReceipt"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: rent-receipt-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rent-receipt-db-secret
              key: password
        ports:
        - containerPort: 8080
      - name: rent-receipt-db
        image: cristobalmilla/rent-receipt-db:latest
        env:
        - name: POSTGRES_DB
          value: "KartingRMRentReceipt"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rent-receipt-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rent-receipt-db-secret
              key: password
        ports:
        - containerPort: 5432
