apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: backend
spec:
  selector:
    app: report
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
