apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
      - name: report-service
        image: cristobalmilla/report-service:latest
        env:
        - name: EUREKA_HOST
          value: "eureka-service.backend.svc.cluster.local"
        - name: EUREKA_PORT
          value: "8761"
        - name: CONFIG_SERVER_URI
          value: "http://config-server.backend.svc.cluster.local:8081"
        ports:
        - containerPort: 8080
