apiVersion: v1
kind: Service
metadata:
  name: special-day-fee-service
  namespace: backend
spec:
  selector:
    app: special-day-fee
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
