apiVersion: v1
kind: Service
metadata:
  name: fee-type-postgres-service # This will be the DNS name for your service
  namespace: backend
  labels:
    app: kartingrm
    component: fee-type-postgres
spec:
  selector:
    app: kartingrm
    component: fee-type-postgres
  ports:
    - protocol: TCP
      port: 5432       # Port inside the cluster for other services to connect
      targetPort: 5432 # Port on the Pod that the service targets
  type: ClusterIP      # Default, for internal cluster access only