apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frequency-postgres-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage
  # storageClassName: standard # Uncomment if your Minikube needs a specific storage class, often 'standard' or 'hostpath'