apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: kartingrm-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30555 # Ensure this is within Minikube's NodePort range (default: 30000-32767)
  type: NodePort
