apiVersion: v1
kind: Service
metadata:
  name: kartingrm-frontend-service # Name for the frontend service
  namespace: frontend
  labels:
    app: kartingrm
    component: kartingrm-frontend
spec:
  selector:
    app: kartingrm
    component: kartingrm-frontend
  ports:
    - protocol: TCP
      port: 80       # Port the service exposes internally
      targetPort: 80 # Port the container is listening on
      nodePort: 30555 # Choose a port in the 30000-32767 range
  type: NodePort     # Exposes the service on a port on each Node's IP