server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/CristobalMilla/KartingRM/KartingRMBackend/microservices-data-project/
          search-paths: config-data
  application:
    name: config-service
