apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-service-deployment
  namespace: backend
  labels:
    app: kartingrm
    component: config-server-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kartingrm
      component: config-server-service
  template:
    metadata:
      labels:
        app: kartingrm
        component: config-server-service
    spec:
      containers:
      - name: config-server-service
        image: cristobalmilla/config-server-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        envFrom: # Use envFrom to pull all data from ConfigMap
        - configMapRef:
            name: backend-config # Refers to the ConfigMap created earlier
        livenessProbe:
          httpGet:
            path: /actuator/health # Your Docker Compose healthcheck was on /actuator/health
            port: 8081
          initialDelaySeconds: 90 # Increased initial delay as it's a critical dependency
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 250m
            memory: 768Mi
          limits:
            cpu: 750m
            memory: 1.5Gi