apiVersion: v1
kind: Service
metadata:
  name: config-server-service # This will be the DNS name for your Config Server
  namespace: backend
  labels:
    app: kartingrm
    component: config-server-service
spec:
  selector:
    app: kartingrm
    component: config-server-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP # Internal service